// Code generated by eggcrate. DO NOT EDIT.

/*
	/assets/css/app.css
	/assets/css/fa.css
	/assets/js/app.js
*/

package main

var assetData = `Dv+BBAEC/4IAAQwBCgAA/8n/ggADEy9hc3NldHMvY3NzL2FwcC5jc3MsH4sIAAAAAAAA/0rKT6lUqFZIzs/JL7JSKEpNUajlAgQA
AP//liTTXhQAAAASL2Fzc2V0cy9jc3MvZmEuY3NzLB+LCAAAAAAAAP/SS0tUqFZIzs/JL7JSSMopTVWo5QIEAAD//8gygUoUAAAA
ES9hc3NldHMvanMvYXBwLmpzMR+LCAAAAAAAAP9KzEktKtFQykjNyclXSE1PTy5KLElV0rTmAgQAAP//X1aDaRkAAAA=`
